### ISSUE TITLE
Puts from the PyDM Widgets Interfere with GUI updates

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/skywalker#18]
Confirmed for YAG position and Slit Width, probably happens for the mirror positions too, but we haven't moved them manually from the GUI.

During these puts, the image and centroid updates freeze.

**Comment by hhslepicka** [comment]
@ZLLentz does the same happens if you have a UI file with the image and text fields only to set the positions?

**Comment by ZLLentz** [comment]
@hhslepicka I'll pull up the smallest test case and rule out a pydm bug.

**Comment by ZLLentz** [comment]
@hhslepicka This problem went away with the most basic image/line edit test. Unfortunately (or fortunately?), it also went away in the main application. I expect this issue was caused by some external factor. I will try again on Tuesday, when beam is done and I can move more things.

**Comment by hhslepicka** [comment]
Were you running it through SSH?

**Comment by ZLLentz** [comment]
All tests and runs have been through SSH so far. I haven't had direct access to a control machine.
