### ISSUE TITLE
Slit readbacks occassionally display too many sig figs during motion

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/skywalker#20]
Stretches the whole gui in a comical way

**Comment by hhslepicka** [comment]
@ZLLentz .... Which widget is being used? I saw similar issue with a previous release when using the PyDMLabel...

**Comment by ZLLentz** [comment]
PyDMLabel, I'll update to a more recent release for future testing.

**Comment by ZLLentz** [comment]
Closing because we're using the most recent PyDM now
