### ISSUE TITLE
GUI Fails to load if any configured object is offline

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/skywalker#31]
If the offending object is not along your path, you shouldn't have to worry about it. The GUI should catch the exception and remove disconnected objects from the combo and selection boxes.

**Comment by ZLLentz** [comment]
This is actually raised in the homs_system call from pswalker. Perhaps this is more of a reason to switch to the config files.

**Comment by teddyrendahl** [comment]
Should be closed by #44
