### ISSUE TITLE
Investigate Qt4 vs. Qt5.

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/skywalker#4]
Had an issue getting a working environment in Qt5, Qt4 seemed to work. Hesitant to investigate until https://github.com/slaclab/pydm/issues/64 is resolved

# packages in environment at /reg/g/pcds/pyps/conda/rhel6/envs/skywalker-app:
#
asn1crypto                0.22.0                   py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
bluesky                   0.9.0            py36ha9dd72c_0    lightsource2-tag
boltons                   17.1.0                   py36_0    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
coverage                  4.4.1                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
databroker                0.9.0            py36h0959367_0    lightsource2-tag
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
doct                      1.0.3            py36h4a913d2_0    lightsource2-tag
epics-base                3.14.12.6            h6af44bd_2    lightsource2-tag
event-model               1.2.0            py36h05e016c_1    lightsource2-tag
exec-wrappers             1.0.3                    py36_0    conda-forge
expat                     2.2.1                         0    conda-forge
filestore                 0.8.0            py36h29e527f_0    lightsource2-tag
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5py                      2.7.0           np113py36h8d4410d_1    lightsource2-tag
hdf5                      1.10.1                        0    conda-forge
historydict               1.2.0                    py36_0    lightsource2-tag
humanize                  0.5.1                    py36_0    conda-forge
hypothesis                3.23.0                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.6                      py36_0  
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.30                        1  
libtiff                   4.0.6                         7    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
lmfit                     0.9.7                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
metadatastore             0.7.0            py36h26b5bd1_0    lightsource2-tag
mkl                       2017.0.3                      0  
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    conda-forge
numpy                     1.13.1                   py36_0  
olefile                   0.44                     py36_0    conda-forge
openssl                   1.0.2l                        0    conda-forge
ophyd                     0.6.1            py36h6cc4f2d_0    lightsource2-tag
pandas                    0.20.3                   py36_1    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pims                      0.4                      py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
prettytable               0.7.2                    py36_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.2.2                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyepics                   3.2.6            py36he7cf0e8_1    lightsource2-tag
pygments                  2.2.0                    py36_0    conda-forge
pymongo                   3.4.0                    py36_0  
pympler                   0.5                      py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyqtgraph                 0.10.0                   py36_2    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytest                    3.2.1                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
scipy                     0.19.1              np113py36_0  
setuptools                36.3.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
simplejson                3.11.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
slicerator                0.9.8                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
super_state_machine       1.0              py36h10e9b35_0    lightsource2-tag
tifffile                  0.12.1              np113py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.8.2                    py36_0    conda-forge
tornado                   4.5.2                    py36_0  
traitlets                 4.3.2                    py36_0    conda-forge
tzlocal                   1.4                      py36_0    conda-forge
ujson                     1.35                     py36_0  
urllib3                   1.22                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xray-vision               0.0.7            py36h729047d_0    lightsource2-tag
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.4.2                    py36_0  

# packages in environment at /reg/g/pcds/pyps/conda/rhel6/envs/skywalker-app-qt4:
#
asn1crypto                0.22.0                   py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
bluesky                   0.9.0            py36ha9dd72c_0    lightsource2-tag
boltons                   17.1.0                   py36_0    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
coverage                  4.4.1                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
databroker                0.9.0            py36h0959367_0    lightsource2-tag
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
doct                      1.0.3            py36h4a913d2_0    lightsource2-tag
epics-base                3.14.12.6            h6af44bd_2    lightsource2-tag
event-model               1.2.0            py36h05e016c_1    lightsource2-tag
exec-wrappers             1.0.3                    py36_0    conda-forge
expat                     2.2.1                         0    conda-forge
filestore                 0.8.0            py36h29e527f_0    lightsource2-tag
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
graphite2                 1.3.9                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5py                      2.7.0           np113py36h8d4410d_1    lightsource2-tag
harfbuzz                  1.4.3                         0    conda-forge
hdf5                      1.10.1                        0    conda-forge
historydict               1.2.0                    py36_0    lightsource2-tag
humanize                  0.5.1                    py36_0    conda-forge
hypothesis                3.23.0                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.6                      py36_0  
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.30                        1  
libtiff                   4.0.6                         7    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
lmfit                     0.9.7                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                1.5.3               np113py36_8    conda-forge
metadatastore             0.7.0            py36h26b5bd1_0    lightsource2-tag
mkl                       2017.0.3                      0  
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    conda-forge
numpy                     1.13.1                   py36_0  
olefile                   0.44                     py36_0    conda-forge
openssl                   1.0.2l                        0    conda-forge
ophyd                     0.6.1            py36h6cc4f2d_0    lightsource2-tag
pandas                    0.20.3                   py36_1    conda-forge
pango                     1.40.4                        0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pims                      0.4                      py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
prettytable               0.7.2                    py36_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.2.2                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyepics                   3.2.6            py36he7cf0e8_1    lightsource2-tag
pygments                  2.2.0                    py36_0    conda-forge
pymongo                   3.4.0                    py36_0  
pympler                   0.5                      py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      4.11.4                   py36_2    conda-forge
pyqtgraph                 0.10.0                   py36_2    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytest                    3.2.1                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        4.8.7                         7    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
scipy                     0.19.1              np113py36_0  
setuptools                36.3.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
simplejson                3.11.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
slicerator                0.9.8                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
super_state_machine       1.0              py36h10e9b35_0    lightsource2-tag
tifffile                  0.12.1              np113py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.8.2                    py36_0    conda-forge
tornado                   4.5.2                    py36_0  
traitlets                 4.3.2                    py36_0    conda-forge
tzlocal                   1.4                      py36_0    conda-forge
ujson                     1.35                     py36_0  
urllib3                   1.22                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xray-vision               0.0.7            py36h729047d_0    lightsource2-tag
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.4.2                    py36_0

**Comment by hhslepicka** [comment]
@teddyrendahl what was the issue?

**Comment by ZLLentz** [comment]
qt5 launched today and resolved the segfault/malloc/free bugs we were seeing in qt4

**Comment by teddyrendahl** [comment]
I think we can attribute this to the the `pyqt` vs `PyQt5` / pip vs. conda battle. Also PyDM will deprecate Qt4!
